### PR TITLE
ENH: drop piezo implementation for new M1L0/M2L0 pitch actuators

### PR DESCRIPTION
**Pull request by nrwslac**
Mechatronics team removed and replaced the the pitch motors on MR1L0 and MR2L0. The performance of these new motors is better and so far have not needed the extra piezo support.  For now, the Piezos will be disabled. If there is a need for them, we can re-enable them. These are the same motors installed on the pitch axes in the XRT, and M1K4, M1K1(yet to be checked out) in the FEE.

### CODE REVIEW

**Comment by ZLLentz** [comment]
> No description provided.

Sorry, I'm a bit out of the loop- what's the context on this?

**Comment by nrwslac** [comment]
> > No description provided.
> 
> Sorry, I'm a bit out of the loop- what's the context on this?

Updated description.

**Review by ZLLentz — APPROVED** [review]
Summarizing the changes I see:
- Reference velocities updated for the new motors
- Tuning tweaks and readback averaging for the new motors
- All pitch/piezo control/coordination function blocks have been commented out
- Create new stepper-only control FBs for the pitch axes
- Pitch axes switched to always enabled, presumably for active position correction

LGTM

**Review by klauer — APPROVED** [review]
LGTM (and thanks for the summaries 👍 )

**Pull request merged**
